### ISSUE TITLE
lint: Cannot read property 'failed' of undefined 

### ISSUE THREAD

**Issue by adamdecaf** [wework/speccy#431]
## Detailed description
I'm trying to lint an OpenAPI specification and it seems to be failing recently. This specification passes in the [Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/moov-io/api/035bf3f5eece59b9b396ce2e3ae59f5f8f6b4a8a/openapi.yaml), but it seems multiple specification files cause it to fail? This has been working for over a year, so I'm at a loss what's going on

Specification: https://raw.githubusercontent.com/moov-io/api/035bf3f5eece59b9b396ce2e3ae59f5f8f6b4a8a/openapi.yaml 

```
$ npm --version 
6.14.8
```
```
$ speccy --version
0.11.0
```

```
$ speccy  lint -v https://raw.githubusercontent.com/moov-io/api/65d1f4e8e5060345fe9f78b9020cfcba33983fba/openapi.yaml 
READ /usr/local/lib/node_modules/speccy/rules/default.yaml
Found 17 rules in default: parameter-description,parameter-name-regex,operation-operationId,operation-summary-or-description,operation-tags,path-keys-no-trailing-slash,server-trailing-slash,openapi-tags,openapi-tags-alphabetical,reference-no-other-properties,example-value-or-externalValue,default-and-example-are-redundant,reference-components-regex,no-script-tags-in-markdown,info-contact,license-apimatic-bug,no-eval-in-descriptions
GET https://raw.githubusercontent.com/moov-io/api/65d1f4e8e5060345fe9f78b9020cfcba33983fba/openapi.yaml
GET https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/components/securitySchemes/GatewayAuth
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/components/securitySchemes/LoginAuth
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1authentication~1authenticated
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1identities
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1identities~1%7BidentityID%7D
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1identities~1%7BidentityID%7D~1credentials
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1identities~1%7BidentityID%7D~1credentials~1%7BcredentialID%7D
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1invites
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1invites~1%7BinviteID%7D
CACHED https://raw.githubusercontent.com/moov-io/identity/master/api/api.yml #/paths/~1authentication~1register
GET https://raw.githubusercontent.com/moov-io/customers/master/api/client.yaml #/paths/~1customers
TypeError: Cannot read property 'failed' of undefined
    at /usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:96:90
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:38:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at resolveAllFragment (/usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:49:9)
    at /usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:236:28
TypeError: Cannot read property 'failed' of undefined
    at /usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:96:90
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:38:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at resolveAllFragment (/usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:49:9)
    at /usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:236:28
TypeError: Cannot read property 'failed' of undefined
    at /usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:96:90
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:38:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at recurse (/usr/local/lib/node_modules/speccy/node_modules/reftools/lib/recurse.js:53:13)
    at resolveAllFragment (/usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:49:9)
    at /usr/local/lib/node_modules/speccy/node_modules/oas-resolver/index.js:236:28
Cannot read property 'failed' of undefined
```

**Comment by MikeRalphson** [comment]
Bug in `oas-resolver` fixed in v`2.5.1`. If you rebuild speccy / your dependent projects this should be fixed. Thanks for the detailed bug report.

**Comment by adamdecaf** [comment]
Thanks for the quick response! Can we get a release of speccy? I was just trying to `npm install speccy` in a Dockerfile. 

https://github.com/moov-io/api/blob/master/Dockerfile#L4

**Comment by MikeRalphson** [comment]
Speccy is unmaintained and I don't have release permissions for it. If your previous build brought in `oas-resolver` @ `2.5.0` (which it must have done to trigger this bug) then installing it the same way should now bring in `2.5.1`.

**Comment by adamdecaf** [comment]
That works for me locally, thanks!
