### ISSUE TITLE
npm cli can't open lint rules file

### ISSUE THREAD

**Issue by jblazek** [wework/speccy#8]
I was able to run `speccy lint`, and wanted to try a local custom rules file. When I do this, I get an error that looks like speccy is looking in my profile for the file.

This happens for a file that exists in the current directory as well as an HTTP resource.

### Checklist

None of the checklist applied to this scenario.

### Detailed Description

1. installed npm package with `npm install -g speccy`
1. ran `speccy lint spec.yaml`, got a validation rule I don't care about
1. made a copy of `default.json` and removed the rule for contact info
1. ran `speccy lint -r custom.json spec.yaml`, got the error below.
1. ran `speccy lint -r http://source/raw/rules spec.yaml`, got the same error except the file tried was `C:\Users\jblazek\AppData\Roaming\npm\node_modules\speccy\rules\http://source/raw/rules.json`
 * note my incoming param didn't have a .json extension but it gets added.

I'm using Windows 10, and tried from powershell and bash with the same result.

```text
Error: ENOENT: no such file or directory, open 'C:\Users\jb\AppData\Roaming\npm\node_modules\speccy\rules\custom.json.json'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at deepMergeRules (C:\Users\jb\AppData\Roaming\npm\node_modules\speccy\lib\linter.js:13:22)
    at Object.loadRules (C:\Users\jb\AppData\Roaming\npm\node_modules\speccy\lib\linter.js:38:42)
    at Command.command (C:\Users\jb\AppData\Roaming\npm\node_modules\speccy\lint.js:79:10)
    at Command.listener (C:\Users\jb\AppData\Roaming\npm\node_modules\speccy\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (C:\Users\jb\AppData\Roaming\npm\node_modules\speccy\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\jb\AppData\Roaming\npm\node_modules\speccy\node_modules\commander\index.js:474:21)
```

**Comment by jblazek** [comment]
I just saw in the docs now that there's only support for the built-in rule sets now. Feel free to close this if adding support is already on your roadmap.
